'use strict';
/* ================================================================
   Season Runner — static data: seasons, skins, i18n strings
================================================================ */

const SR = {};
SR.reportError = __srReportError;   // defined in util.js

/* ---------- Seasons ---------- */
SR.SEASONS = [
  {
    id: 'spring', emoji: '🌸', color: '#7ec850',
    name: { ar: 'الربيع', en: 'Spring' },
    order: 0, unlockGems: 0,
    speedMul: 1.0, gravity: 2300, jumpV: 800, slideBoost: 1.06,
    skyTop: '#69c8f2', skyMid: '#a9e4ff', skyBottom: '#e8f9ff',
    sun: { x: 760, y: 110, r: 46, color: '#fff3b0' },
    mountFar: '#8fcd8f', mountMid: '#6fb86f',
    groundTop: '#8fd464', groundDeep: '#5aa53e', groundEdge: '#b7ef8c',
    deco: ['sakura', 'bush', 'flower2'],
    ambient: 'petals', storm: null,
    tile: 'grass', tileColor: '#6dbf52',
    music: { bpm: 103, root: 64, scale: [0, 2, 4, 7, 9], leadWave: 'triangle', bassWave: 'sine',
      chords: [[64, 68, 71], [60, 64, 67], [67, 71, 74], [62, 66, 69]], hat: false, pad: false, kick: true, arp: true },
    obstaclePool: ['branch', 'bee', 'mud', 'flower'],
    particles: [[233, 30, 99], [255, 143, 179], [255, 255, 255]],
  },
  {
    id: 'summer', emoji: '☀️', color: '#ff9f43',
    name: { ar: 'الصيف', en: 'Summer' },
    order: 1, unlockGems: 1,
    speedMul: 1.22, gravity: 2700, jumpV: 830, slideBoost: 1.12,
    skyTop: '#2ba7e8', skyMid: '#59c4f0', skyBottom: '#ffe3a0',
    sun: { x: 620, y: 96, r: 60, color: '#fff0b8' },
    mountFar: '#e2b571', mountMid: '#c9944f',
    groundTop: '#f2d492', groundDeep: '#d9a75c', groundEdge: '#fff0c0',
    deco: ['cactus', 'rock', 'dune'],
    ambient: 'heat', storm: 'sand',
    tile: 'sand', tileColor: '#e8c078',
    music: { bpm: 136, root: 57, scale: [0, 3, 5, 7, 10], leadWave: 'square', bassWave: 'triangle',
      chords: [[57, 60, 64], [53, 57, 60], [60, 64, 67], [55, 58, 62]], hat: true, pad: false, kick: true, arp: true },
    obstaclePool: ['fire', 'cactus', 'lens'],
    particles: [[255, 183, 77], [255, 143, 0], [255, 235, 59]],
  },
  {
    id: 'autumn', emoji: '🍂', color: '#e07b39',
    name: { ar: 'الخريف', en: 'Autumn' },
    order: 2, unlockGems: 3,
    speedMul: 1.08, gravity: 2450, jumpV: 815, slideBoost: 1.1,
    skyTop: '#8e6f86', skyMid: '#c98f6d', skyBottom: '#f7d9a8',
    sun: { x: 820, y: 150, r: 40, color: '#ffd9a0' },
    mountFar: '#b57b57', mountMid: '#93553a',
    groundTop: '#c98244', groundDeep: '#96542b', groundEdge: '#e0a468',
    deco: ['oaktree', 'rock', 'stump'],
    ambient: 'leaves', storm: null,
    tile: 'leaves', tileColor: '#b06a34',
    music: { bpm: 92, root: 62, scale: [0, 2, 3, 5, 7, 9, 10], leadWave: 'triangle', bassWave: 'sine',
      chords: [[62, 65, 69], [57, 60, 64], [60, 64, 67], [65, 68, 72]], hat: false, pad: true, kick: true, arp: false },
    obstaclePool: ['pile', 'whirl', 'mushroom', 'fox'],
    particles: [[214, 90, 40], [240, 150, 60], [190, 110, 40]],
  },
  {
    id: 'winter', emoji: '❄️', color: '#8fd4f0',
    name: { ar: 'الشتاء', en: 'Winter' },
    order: 3, unlockGems: 5,
    speedMul: 0.92, gravity: 2050, jumpV: 790, slideBoost: 1.05, friction: 0.985,
    skyTop: '#4d7296', skyMid: '#7fa6c4', skyBottom: '#c9dcec',
    sun: { x: 170, y: 120, r: 36, color: '#dcecf7' },
    mountFar: '#a8c6de', mountMid: '#7fa0bd',
    groundTop: '#eaf4fb', groundDeep: '#c3d9e8', groundEdge: '#ffffff',
    deco: ['pine', 'rock', 'snowbush'],
    ambient: 'snow', storm: 'snow',
    tile: 'snow', tileColor: '#d7e8f4',
    music: { bpm: 76, root: 55, scale: [0, 2, 3, 5, 7], leadWave: 'sine', bassWave: 'sine',
      chords: [[55, 59, 62], [50, 54, 57], [53, 57, 60], [58, 62, 65]], hat: false, pad: true, kick: false, arp: true },
    obstaclePool: ['icefall', 'snowman', 'bear'],
    particles: [[255, 255, 255], [190, 225, 245], [150, 200, 230]],
  },
];

SR.getSeason = i => SR.SEASONS[((i % 4) + 4) % 4];
SR.unlockedSeasons = progress => {
  const g = progress.gems || 0;
  let n = 1;
  if (g >= 1) n = 2;
  if (g >= 3) n = 3;
  if (g >= 5) n = 4;
  return n;
};

/* ---------- Skins ---------- */
SR.SKINS = [
  { id: 'nuro', name: { ar: 'نورو', en: 'Nuro' }, glow: '#8effc1', body: '#5ce8a0', cost: 0 },
  { id: 'sunset', name: { ar: 'غروب', en: 'Sunset' }, glow: '#ffb35c', body: '#ff9d45', cost: 500 },
  { id: 'rose', name: { ar: 'وردة', en: 'Rose' }, glow: '#ff8fc0', body: '#ff7db4', cost: 800 },
  { id: 'midnight', name: { ar: 'منتصف الليل', en: 'Midnight' }, glow: '#b39cff', body: '#9a7fff', cost: 1200 },
  { id: 'ice', name: { ar: 'جليد', en: 'Ice' }, glow: '#9fe8ff', body: '#8fdcf5', cost: 1500 },
  { id: 'gold', name: { ar: 'ذهبي', en: 'Golden' }, glow: '#ffd94d', body: '#ffcf3d', cost: 2500 },
];

/* ---------- i18n ---------- */
SR.LANG = {
  ar: {
    'menu.sub': 'مغامرة الفصول الأربعة',
    'menu.start': '▶ ابدأ الجري',
    'menu.stats': '🏆 الأرقام القياسية',
    'menu.skins': '🎨 السكانات',
    'menu.settings': '⚙️ الإعدادات',
    'menu.story': '📖 القصة',
    'menu.howto': '❓ طريقة اللعب',
    'hud.m': 'م',
    'hud.hint': 'اضغط للقفز 👆',
    'hud.hint2': 'سحب لتحت = انزلاق • ضغطة طويلة = إنطلاقة 💨',
    'stats.title': '🏆 الأرقام القياسية',
    'stats.bestDist': 'أطول مسافة',
    'stats.bestScore': 'أعلى نقاط',
    'stats.bestStreak': 'أطول سلسلة',
    'stats.runs': 'عدد الجولات',
    'stats.totalLeaves': 'إجمالي الأوراق',
    'stats.totalGems': 'إجمالي الشظايا',
    'stats.top5': '🏅 أفضل 5 جولات محليًا',
    'stats.back': '← رجوع',
    'stats.empty': 'ما زلت ما لعبتش… العب أول جولة! 🎮',
    'skins.title': '🎨 السكانات',
    'skins.buy': 'اشترِ',
    'skins.select': 'اختيار',
    'skins.selected': '✓ مُختار',
    'skins.owned': 'مملوك ✓',
    'skins.locked': 'قفل 🔒',
    'skins.notEnough': 'الأوراق مش كفاية! 🍃',
    'settings.title': '⚙️ الإعدادات',
    'settings.sound': '🔊 المؤثرات الصوتية',
    'settings.music': '🎵 الموسيقى',
    'settings.vibrate': '📳 الاهتزاز',
    'settings.language': '🌐 اللغة',
    'settings.reset': '🗑️ مسح كل التقدم',
    'settings.resetBtn': 'مسح',
    'settings.resetConfirm': 'متأكد؟ هيتحذف كل تقدمك نهائيًا!',
    'settings.about': 'Season Runner v1.0.2 — لعبة Endless Runner بفصول متغيرة. صُنعت بحب 💚',
    'story.title': '📖 قصة نورو',
    'story.prologue': 'نورو، روح الطبيعة الصغيرة، تحرس جوهرة التوازن التي تضبط إيقاع الفصول الأربعة. لكن ملك الفوضى سرقها! انكسرت الجوهرة إلى شظايا متناثرة، واختلطت الفصول: صيفٌ يحرق الربيع، وثلجٌ يغطي الخريف… والآن يجب أن تجري نورو عبر عالم متغير بلا توقف لتجمع الشظايا وتعيد التوازن قبل أن ينهار كل شيء!',
    'story.locked': '🔒 أُفتح بـ 💎 {n}',
    'story.unlocked': '✓ مفتوح',
    'story.ch1t': '🌸 الربيع',
    'story.ch1': 'أول شظايا الجوهرة سقطت في الحدائق المزهرة. اهرب من النحل، انزلق تحت الأغصان، واستعد لتوازن الفصول!',
    'story.ch2t': '☀️ الصيف',
    'story.ch2': 'شمس حارقة وصحراء لا ترحم. أعمدة النار والصبار المتحرك في انتظارك… اجمع الشظية قبل أن تحترق الأرض!',
    'story.ch3t': '🍂 الخريف',
    'story.ch3': 'غابة من الأوراق المتساقطة تخفي الأسرار، ودوامات الهواء تحمل الفوضى. واصل الجري في الضباب!',
    'story.ch4t': '❄️ الشتاء',
    'story.ch4': 'الجليد يزحف على كل شيء، والدببة نائمة… حتى تُزعجها. الشظية الأخيرة هناك، خلف عاصفة الثلج. واجه الفوضى وأنقذ التوازن!',
    'story.epilogue': '✨ أعادت نورو التوازن إلى الطبيعة! تعود الفصول إلى إيقاعها الجميل… حتى تظهر شظية جديدة في الأفق؟',
    'howto.title': '❓ طريقة اللعب',
    'howto.tap': '👆 ضغطة واحدة',
    'howto.tapD': 'قفز فوق العوائق الأرضية',
    'howto.dtap': '👆👆 ضغطتان',
    'howto.dtapD': 'قفز مزدوج في الهواء',
    'howto.swipe': '👇 سحب لتحت',
    'howto.swipeD': 'انزلاق تحت العوائق العلوية',
    'howto.long': '⏳ ضغطة طويلة',
    'howto.longD': 'إنطلاقة 💨 تخترق كل شيء (تتعاد كل ٧ ثوانٍ)',
    'howto.swipeUp': '👆 سحب لفوق',
    'howto.swipeUpD': 'الوقوف أثناء الانزلاق',
    'howto.seasons': '🌸 الفصول تتغير كل ٤٠ ثانية — عوائق جديدة، فيزياء جديدة، وموسيقى جديدة!',
    'howto.tip': '💡 نصيحة: العوائق العلوية تحتاج انزلاق، والأرضية تحتاج قفز!',
    'pause.title': '⏸️ إيقاف مؤقت',
    'pause.resume': '▶ استمرار',
    'pause.restart': '🔄 إعادة الجولة',
    'pause.exit': '🏠 القائمة الرئيسية',
    'death.title': '💀 انتهت الجولة!',
    'death.dist': 'المسافة',
    'death.score': 'النقاط',
    'death.leaves': 'الأوراق',
    'death.gems': 'الشظايا',
    'death.newBest': '🎉 رقم قياسي جديد!',
    'death.best': 'أفضل رقم: {n}م',
    'death.revive': '📺 إحياء بإعلان (مرة واحدة)',
    'death.retry': '🔄 حاول تاني',
    'death.share': '📤 شارك',
    'death.menu': '🏠 القائمة',
    'death.shareText': 'أنا قطعت {d}م وجمعت {s} نقطة في Season Runner! 🏃💨 جرب تلحقني!',
    'ad.title': '📺 إعلان تجريبي',
    'ad.note': '(في النسخة النهائية: إعلان حقيقي = إحياء مجاني)',
    'toast.gem': '💎 شظية الجوهرة!',
    'toast.power': '⚡ قوة جديدة!',
    'toast.unlockSummer': '☀️ تم فتح فصل الصيف!',
    'toast.unlockAutumn': '🍂 تم فتح فصل الخريف!',
    'toast.unlockWinter': '❄️ تم فتح فصل الشتاء!',
    'toast.slow': '🐌 الطين يبطئك!',
    'toast.bear': '🐻 أيقظت الدب! اهرب!',
    'toast.storm': '🌪️ عاصفة تقترب…',
    'toast.revive': '💚 واصل الجري!',
    'toast.noAds': 'الإحياء انتهى!',
    'toast.saved': 'تم الحفظ ✓',
    'toast.shareFail': 'مقدرناش نشارك على هذا الجهاز',
    'notif.near': 'قريب! +{n}',
    'notif.combo': '×{n} سلسلة!',
    'notif.star': '⭐ وضع النجمة!',
    'notif.eagle': '🦅 طيران النسر!',
    'notif.freeze': '⏳ تجميد الزمن!',
    'notif.lock': '🔒 تثبيت الفصل!',
    'notif.shield': '🛡️ درع الفصل!',
    'notif.magnet': '🧲 مغناطيس الجوهرة!',
    'notif.dash': '💨 إنطلاقة!',
    'pow.shield': 'درع',
    'pow.magnet': 'مغناطيس',
    'pow.freeze': 'تجميد',
    'pow.eagle': 'نسر',
    'pow.lock': 'تثبيت',
    'pow.star': 'نجمة',
    'go.go': 'انطلق! 🏃',
    'codes.title': '🎁 كود سري',
    'codes.ph': 'اكتب الكود هنا…',
    'codes.redeem': 'استخدم',
    'codes.ok': '🎉 تم! +{leaves} 🍃 و +{gems} 💎',
    'codes.bad': '❌ الكود غير صحيح',
    'codes.used': '⚠️ الكود ده مستخدم قبل كده',
    'codes.usedCount': 'الأكواد المستخدمة: {n}',
    'fatal.title': '😵 حصلت مشكلة في العرض',
    'fatal.msg': 'اللعبة وقفت فجأة. جرّب إعادة المحاولة أو الرجوع للقائمة.',
    'fatal.retry': '🔄 إعادة المحاولة',
    'fatal.menu': '🏠 القائمة الرئيسية',
  },
  en: {
    'menu.sub': 'The Four Seasons Adventure',
    'menu.start': '▶ Start Running',
    'menu.stats': '🏆 Records',
    'menu.skins': '🎨 Skins',
    'menu.settings': '⚙️ Settings',
    'menu.story': '📖 Story',
    'menu.howto': '❓ How to Play',
    'hud.m': 'm',
    'hud.hint': 'Tap to jump 👆',
    'hud.hint2': 'Swipe down = slide • Hold = dash 💨',
    'stats.title': '🏆 Records',
    'stats.bestDist': 'Best distance',
    'stats.bestScore': 'Best score',
    'stats.bestStreak': 'Best streak',
    'stats.runs': 'Runs',
    'stats.totalLeaves': 'Total leaves',
    'stats.totalGems': 'Total gems',
    'stats.top5': '🏅 Local top 5',
    'stats.back': '← Back',
    'stats.empty': 'No runs yet… play your first! 🎮',
    'skins.title': '🎨 Skins',
    'skins.buy': 'Buy',
    'skins.select': 'Select',
    'skins.selected': '✓ Selected',
    'skins.owned': 'Owned ✓',
    'skins.locked': 'Locked 🔒',
    'skins.notEnough': 'Not enough leaves! 🍃',
    'settings.title': '⚙️ Settings',
    'settings.sound': '🔊 Sound FX',
    'settings.music': '🎵 Music',
    'settings.vibrate': '📳 Vibration',
    'settings.language': '🌐 Language',
    'settings.reset': '🗑️ Reset all progress',
    'settings.resetBtn': 'Reset',
    'settings.resetConfirm': 'Are you sure? All progress will be lost!',
    'settings.about': 'Season Runner v1.0.2 — An endless runner with shifting seasons. Made with love 💚',
    'story.title': '📖 Nuro\'s Story',
    'story.prologue': 'Nuro, the little nature spirit, guards the Balance Gem that keeps the four seasons in rhythm. But the Chaos King stole it! The gem shattered into fragments, and the seasons mixed: summer burning spring, snow covering autumn… Now Nuro must run through an ever-changing world, collect the fragments and restore balance before everything collapses!',
    'story.locked': '🔒 Unlock with 💎 {n}',
    'story.unlocked': '✓ Unlocked',
    'story.ch1t': '🌸 Spring',
    'story.ch1': 'The first gem fragments fell into the blooming gardens. Dodge the bees, slide under the branches, and get ready to balance the seasons!',
    'story.ch2t': '☀️ Summer',
    'story.ch2': 'A scorching sun and a merciless desert. Fire pillars and running cacti await… collect the fragment before the land burns!',
    'story.ch3t': '🍂 Autumn',
    'story.ch3': 'A forest of fallen leaves hides secrets, and air whirlwinds carry chaos. Keep running through the mist!',
    'story.ch4t': '❄️ Winter',
    'story.ch4': 'Ice creeps over everything, and bears sleep… until you wake them. The last fragment is there, beyond the blizzard. Face the chaos and restore balance!',
    'story.epilogue': '✨ Nuro restored balance to nature! The seasons return to their rhythm… until a new fragment appears on the horizon?',
    'howto.title': '❓ How to Play',
    'howto.tap': '👆 Tap',
    'howto.tapD': 'Jump over ground obstacles',
    'howto.dtap': '👆👆 Double tap',
    'howto.dtapD': 'Double jump mid-air',
    'howto.swipe': '👇 Swipe down',
    'howto.swipeD': 'Slide under overhead obstacles',
    'howto.long': '⏳ Hold',
    'howto.longD': 'Dash 💨 through anything (7s cooldown)',
    'howto.swipeUp': '👆 Swipe up',
    'howto.swipeUpD': 'Stand up while sliding',
    'howto.seasons': '🌸 Seasons change every 40s — new obstacles, new physics, new music!',
    'howto.tip': '💡 Tip: slide under overhead obstacles, jump over ground ones!',
    'pause.title': '⏸️ Paused',
    'pause.resume': '▶ Resume',
    'pause.restart': '🔄 Restart run',
    'pause.exit': '🏠 Main menu',
    'death.title': '💀 Game Over!',
    'death.dist': 'Distance',
    'death.score': 'Score',
    'death.leaves': 'Leaves',
    'death.gems': 'Gems',
    'death.newBest': '🎉 New record!',
    'death.best': 'Best: {n}m',
    'death.revive': '📺 Revive with ad (once)',
    'death.retry': '🔄 Try again',
    'death.share': '📤 Share',
    'death.menu': '🏠 Menu',
    'death.shareText': 'I ran {d}m and scored {s} in Season Runner! 🏃💨 Try to beat me!',
    'ad.title': '📺 Demo Ad',
    'ad.note': '(Final version: real ad = free revive)',
    'toast.gem': '💎 Balance Gem Fragment!',
    'toast.power': '⚡ Power-up!',
    'toast.unlockSummer': '☀️ Summer unlocked!',
    'toast.unlockAutumn': '🍂 Autumn unlocked!',
    'toast.unlockWinter': '❄️ Winter unlocked!',
    'toast.slow': '🐌 Mud slows you down!',
    'toast.bear': '🐻 You woke the bear! Run!',
    'toast.storm': '🌪️ Storm approaching…',
    'toast.revive': '💚 Keep running!',
    'toast.noAds': 'Revive used!',
    'toast.saved': 'Saved ✓',
    'toast.shareFail': 'Could not share on this device',
    'notif.near': 'Close! +{n}',
    'notif.combo': '×{n} combo!',
    'notif.star': '⭐ Star mode!',
    'notif.eagle': '🦅 Eagle flight!',
    'notif.freeze': '⏳ Time freeze!',
    'notif.lock': '🔒 Season locked!',
    'notif.shield': '🛡️ Season shield!',
    'notif.magnet': '🧲 Gem magnet!',
    'notif.dash': '💨 Dash!',
    'pow.shield': 'Shield',
    'pow.magnet': 'Magnet',
    'pow.freeze': 'Freeze',
    'pow.eagle': 'Eagle',
    'pow.lock': 'Lock',
    'pow.star': 'Star',
    'go.go': 'GO! 🏃',
    'codes.title': '🎁 Secret code',
    'codes.ph': 'Enter code here…',
    'codes.redeem': 'Redeem',
    'codes.ok': '🎉 Redeemed! +{leaves} 🍃 and +{gems} 💎',
    'codes.bad': '❌ Invalid code',
    'codes.used': '⚠️ That code was already used',
    'codes.usedCount': 'Codes redeemed: {n}',
    'fatal.title': '😵 Rendering problem',
    'fatal.msg': 'The game stopped drawing. Try again or go back to the menu.',
    'fatal.retry': '🔄 Try again',
    'fatal.menu': '🏠 Main menu',
  },
};
SR.t = key => {
  let lang = 'ar';
  try { if (typeof SR.save !== 'undefined' && SR.save.progress && SR.save.progress.lang) lang = SR.save.progress.lang; } catch (e) {}
  return (SR.LANG[lang] && SR.LANG[lang][key]) || SR.LANG.ar[key] || key;
};
SR.tf = (key, vars) => {
  let s = SR.t(key);
  for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
  return s;
};
